# Configuration Settings
# See https://gohugo.io/getting-started/configuration/
baseURL = "https://dev.whhone.com/"
# baseURL = "https://whhone.netlify.app/"
languageCode = "en-us"
title = "Wai Hon's Blog"

# https://github.com/Vimux/Mainroad
theme = "mainroad"

# Google Analytics API key.
# googleAnalytics = "UA-38001261-1"

# Disqus Integration. See https://gohugo.io/content-management/comments/.
disqusShortname = "wai-hons-blog"

summaryLength = 25

# Permalinks is the permanent link to a post. It is supposed to be permanent and
# as simple as possible.
#
# - The slug ("/:slug/") is used because it could be permanent is simple.
# - The file name ("/:filename/") is also simple and permanent but it is too
#   make the file name repeats the directory name.
# - The date ("/:year/:month/") is not being used because it makes the link
#   longer. If the post is time-related, we can always include the time in the
#   file name.
# - The title (":title") is not being used because it could be changed after
#   publishing the post.
[permalinks]
  posts = "/:slug/"

[Author]
  name = "Wai Hon Law"
  avatar = "/img/avatar.jpg"
  bio = "Software Engineer at Google, Runner, Reader, Husband, Father."

# The ".Site.Params" Variable.
# See https://gohugo.io/variables/site/#site-variables-list
[Params]
  subtitle = "" # Subtitle of your site. Used in site header
  description = "The Personal Blog of Wai Hon Law (whhone)" # Site description. Used in meta description
  copyright = "Wai Hon Law" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  toc = false # Enable Table of Contents
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["posts"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates
  authorbox = true # Show authorbox at bottom of pages if true
  highlightColor = "#4BB"

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = true # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets.social]
  facebook = "whhone"
  twitter = "whhone"
  # instagram = "whhone"
  # linkedin = "whhone"
  # telegram = "whhone"
  github = "whhone"
  # gitlab = "whhone"
  # bitbucket = "whhone"
  email = "whhone@gmail.com"

#[[menu.main]]
#  name = "Home"
#  url = "/"
#  weight = 2

#[[menu.main]]
#  name = "Feed"
#  url = "http://feeds.feedburner.com/whhone"
#  weight = 10
