# Configuration Settings
# See https://gohugo.io/getting-started/configuration/
baseURL = "https://whhone.com/"
languageCode = "en-us"
title = "Wai Hon's Blog"

# Google Analytics API key.
googleAnalytics = "UA-38001261-1"

# Disqus Integration. See https://gohugo.io/content-management/comments/.
disqusShortname = "wai-hons-blog"

# Permalinks is the permanent link to a post. It is supposed to be permanent and
# as simple as possible.
#
# - The slug ("/:slug/") is used because it could be permanent is simple.
# - The file name ("/:filename/") is also simple and permanent but it is too
#   make the file name repeats the directory name.
# - The date ("/:year/:month/") is not being used because it makes the link
#   longer. If the post is time-related, we can always include the time in the
#   file name.
# - The title (":title") is not being used because it could be changed after
#   publishing the post.
[permalinks]
  posts = "/:slug/"

# The ".Site.Params" Variable.
# See https://gohugo.io/variables/site/#site-variables-list
[params]
  author = "Wai Hon Law"
  avatar = "/img/avatar.jpg"
  bio = "Software Engineer at Google, Runner, Reader, Husband, Father."
  description = "The Personal Blog of Wai Hon Law (whhone)"
  email = "whhone@gmail.com"
  favicon = "/ico/favicon.ico"

  # Social Links
  twitter = "whhone"
  github = "whhone"
  facebook = "whhone"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 2

[[menu.main]]
  name = "RSS"
  url = "/index.xml"
  weight = 10
