baseURL: https://whhone.com/
title: Wai Hon's Blog
paginate: 5
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

googleAnalytics: UA-38001261-1

minify:
    disableXML: true
    minifyOutput: false

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Home
                  url: /
                  weight: 1
                - name: Archives
                  url: archives/
                  weight: 4
                - name: Tags
                  url: tags/
                  weight: 3
                - name: Search
                  url: search/
                  weight: 5
                - name: About
                  url: about/
                  weight: 2
                - name: RSS
                  url: index.xml
                  weight: 6

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    # env: production
    description: "The Personal Blog of Wai Hon Law (whhone)" # Site description. Used in meta description
    # author: Wai Hon Law
    ShowReadingTime: false
    defaultTheme: auto
    ShowShareButtons: false
    displayFullLangName: false
    disableSpecial1stPost: true

taxonomies:
    category: categories
    tag: tags
    series: series

# https://gohugo.io/about/hugo-and-gdpr/
privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true