baseURL = "https://whhone.com/"
languageCode = "en-us"
title = "Wai Hon's Blog"
theme = "hugo_theme_pickles"

# Permalinks is the permanent link to a post. It is supposed to be permanent and
# as simple as possible.
#
# - The file name ("/:filename/") is used because it could be permanent is
#   simple.
# - The date ("/:year/:month/") is not being used because it makes the link
#   longer. If the post is time-related, we can always include the time in the
#   file name.
# - The title (":title") is not being used because it could be changed after
#   publishing the post.
[permalinks]
  posts = "/:filename/"

# Theme's configuration.
#
# See https://github.com/mismith0227/hugo_theme_pickles/blob/release/exampleSite/config.toml
[params]
  favicon = "/favicon.ico"
  avatar = "/zurich.jpg"
  author = "Wai Hon Law"
  bio = "Software Engineer, Runner, Husband, Father."
  contact = "mailto:whhone@gmail.com"

  twitter = "whhone"
  github = "whhone"
  ga_api_key  = "UA-38001261-1"
