#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: posts

* Posts

** DONE From Evernote to Org-Mode :linux:emacs:privacy:personal_development:
SCHEDULED: <2020-09-03 Thu>
:PROPERTIES:
:EXPORT_DATE: 2020-09-03
:EXPORT_FILE_NAME: from-evernote-to-org-mode
:EXPORT_HUGO_SLUG: from-evernote-to-org-mode
:END:
:LOGBOOK:
CLOCK: [2020-09-03 Thu 09:40]--[2020-09-03 Thu 15:55] =>  6:15
:END:

Since 2017, Evernote has been my [[/productivity-system][productivity system]] for note-taking and task management. It has served me very well and I became a paid user. However, mentioned in the [[/arch-linux-full-disk-encryption/][last post]], I am pursuing more privacy in my digital life and Evernote becomes a loophole.

This post talks about the privacy concern, my research on the alternatives, and the switch to Org-Mode.

*** 1. The Privacy Concern of Evernote

The user data in Evernote is [[https://evernote.com/security][encrypted "during transport" and "at-rest"]]. This sounds secure to readers but actually not enough because Evernote can still see the content. Technically, it is still server-side encryption instead the client-side encryption (a.k.a. end-to-end encryption). The encryption key of the note content is held by the server instead of the client. If the server is hacked, or there is an evil employee, or Evernote needs to comply with legal obligations (i.e., the government asks for user data, and [[https://evernote.com/privacy/transparency-report][it does]]), those notes could be leaked.

*** 2. Researching the Alternatives

I started researching the alternatives which do not compromise privacy. That means end-to-end encryption is required if the data is hosted on a third-party. This requirement actually simplifies my curation because many solutions are ruled out, including the popular Notion and Roam (o:

My final shortlist included [[https://orgmode.org/][*Org-Mode*]], [[https://joplinapp.org/][*Joplin*]], [[https://standardnotes.org/][*Standard Note*]], [[https://taskwarrior.org/][*Taskwarrior*]], [[http://todotxt.org/][*TODO.txt*]], and [[https://tiddlywiki.com/][*TiddlyWiki*]]. I gave each of them a try, reviewed and scored them with my requirements.

|                     | *Evernote* | *Org-Mode* | *Joplin* | *Standard Note* | *Taskwarrior* | *TODO.txt* | *TiddlyWiki* |
|---------------------+------------+------------+----------+-----------------+---------------+------------+--------------|
| *Privacy*           |          1 |          5 |        5 |               5 |             5 |          5 | 5            |
| *Task Management*   |          4 |          5 |        1 |               1 |             5 |          5 | ?            |
| *Task Context*      |          5 |          4 |        4 |               5 |             2 |          1 | ?            |
| *Linux Usability*   |          4 |          5 |        4 |               4 |             3 |          3 | ?            |
| *Android Usability* |          5 |          3 |        3 |               4 |             2 |          2 | ?            |
| *Synchronization*   |          5 |          4 |        5 |               5 |             4 |          4 | ?            |
|---------------------+------------+------------+----------+-----------------+---------------+------------+--------------|
| *Total*             |         24 |         26 |       22 |              24 |            21 |         20 | ?            |

*Requirements:*
- *Privacy*: Can I seclude my data?
- *Basic Task Management*: Can I set a date for a task and then view all tasks for today?
- *Task Context*: Can I add references (instruction, link) to the task?
- *Linux Usability*: How usable is it on Linux?
- *Android Usability*: How usable is it on Android?
- *Synchronization*: How hard is it to synchronize data between Linux and Android?

**** Review: Evernote (24)

Evernote has a reminder feature for simple task management, which is already enough for me. Since it is a note-taking app, I can add rich context like images or even audio seamlessly. Tusk makes it usabe on Linux and the official Android app is simply awesome. Synchronization works out-of-the-box.

However, it fails on the privacy bit.

**** Review: Org-Mode (26)

Org-Mode is for keeping notes, maintaining TODO lists, planning projects, and authoring documents with a fast and effective plain-text system. It is absolutely capable.

However, the learning curve of Org-Mode is steep and even steeper for non-Emacs users. Users are expected to read documentation and practice. Once familiarized with Emacs, its usability on Linux will jump from 0 to 5 (or even infinity). The Android client Orgzly is usable but could be better. Synchronization works with SyncThing.

**** Review: Joplin (22) and Standard Note (24)

Joplin and Standard Note are both strong note-taking alternatives to Evernote. However, they suck in task management because they simply cannot show all tasks scheduled for today. They both have a decent desktop app written in Electron. Synchronization works natively and usesr can turn on end-to-end encryption for privacy/security.

If task management is not a requirement, both Joplin and Standard Note are very good alternatives.

**** Review: Taskwarrior (21) and TODO.txt (20)

Taskwarrior and TODO.txt are both FOSS for task management. However, they both allow only one line per task, which makes adding extra context to the task very hard. Their clients are barely usable to me (or I have not learned enough). Secure synchronization works with a self-hosted server or with SyncThing for Taskwarrior and TODO.txt respectively.

**** Review: TiddlyWiki (?)

TiddlyWiki is a "non-linear personal web notebook". It looks fancy but I haven't tried it intensively because Org-Mode seems working for me already at this point. I will leave it as a question mark.

*** 3. Switching to Org-Mode

After all these explorations, Org-Mode looks promising to me and I started the Org-Mode/Emacs 30-day challenge -- keep using Org-Mode/Emacs for a month. Note that I was still using Evernote during the transition but gradually reducing the dependency on it.

I have now finished the challenge and can claim myself an Org-Mode user. I am happy with Org-Mode and the new workflow. Since the org files are in plain text, I manage my notes with Git, review, and polish all the changes before committing it. It helps to improve the quality of my notes!

Beyond Org-Mode, I also started seeing the beauty of Emacs and why people use it instead of Vim or other modern editors. Emacs is ostensibly an editor but actually a powerful Lisp platform/runtime, which makes it super extensible and capable. I am now using Emacs even more. For example, I replace Visual Studio Code, my previous editor/git porcelain, with  [[https://magit.vc/][Magit]]. This blog post is written in Emacs with [[https://ox-hugo.scripter.co/][ox-hugo]]. I probably will blog on these topics sometime in the future.

All in all, I am very happy with the privacy gain and the learning from this switch!

** Design The New System
When switching, I promise myself that I will use and learn the tool mindfully, with curiosity. The same when I reinstalling arch linux with full Disk Encryption. I promise myself I will use it with awareness. Make it the last OS I am going to use. Don't break it again.

I have started using Emacs Org Mode for note taking and TODO management (an alternative to Evernote) since August 2020 as one of the steps to pursuit more privacy.

Before that, I thought Evernote was my ultimate note-taking + TODO app and it did work for me for 2 years. However, during the days when I was using Emacs Org Mode, I was very happy to use a *real* TODO app, that supports, for examples,
- priority :: this helps sorting the daily TODO
- repeated task :: when setting it right, it reduce the little friction to update the date in the future
- optional time :: Setting time optionally makes sense
- due date :: Setting due date and scheduled date

 However, there is no best app. Org Mode wins the TODO game but not the note taking, and the cross-platform games.
 - Org Mode's plain text note is harder to read.
 - Org Mode's UI is poor. User need to remember the file names to navigate around.
 - Org Mode does not have a decent Android app as well.

 This dilemma inspired me to re-think and re-design my productivity system, my workflow, and the apps I use. I started by listing my user stories.

 P0 Features
 - Inbox for capturing, image and voice are a plus.
 - Note taking when I am reading a book, essay, taking course, or even researching, or storing code Snippet. The format does not matter here.
 - Solid TODO with scheduled date/time. I call it "self-programming"
 - Personal Knowledge Management (Everything in my own word, my principles, error logs, reflection, etc)
 - Personal Information Management
 - Privacy, Security

 For example, the table below is still a raw note that helps me thinking.

 |                   |  Inbox / Capture | TODO                    | Raw Note               |  Knowledge (version control) |                 Habit | Daily Journal | Search | Sync (L <-> A)    | Privacy |
 |-------------------+------------------+-------------------------+------------------------+------------------------------+-----------------------+---------------+--------+-------------------+---------|
 | *Goal*            | Capture Anything | *Program Myself*        | Unstructured Note      |    PIM, Principles, Decision |                       |  Activity Log |        |                   |         |
 | *Tool*            |         Evernote | Org-Mode, +Evernote+    | Evernote, +Org-Mode+   | Org-Mode, Blog, Wiki, Z-note |                       |               |        |                   |         |
 | *Example*         |                  |                         | Reading, Coursera Note |                              |                       |               |        |                   |         |
 | *Requirements*    |                  |                         |                        |    Strong-Linking, Reference |                       |               |        |                   |         |
 | *Cross-Platform?* |              YES | YES                     | YES                    |                           NO |                       |               |        |                   |         |
 |-------------------+------------------+-------------------------+------------------------+------------------------------+-----------------------+---------------+--------+-------------------+---------|
 | Evernote *        |              *5* | 3, priority, repeat     | 5                      |                            3 | 3, Recurring Reminder |             4 |      4 | 5, Native         |       2 |
 | Org-Mode          | 3, photo, mobile | 4, Text UI              | 3, .org, mobile        |                            4 |                       |             3 |      4 | 4, with SyncThing |       5 |
 | Notion *          |        3, mobile | 2                       | 4                      |                         4.5? |                     1 |             4 |      4 | 4, Mobile Web (o: |       1 |
 | Joplin            |                4 | 2, priority, repeat, UI | 4, markdown (o:        |                            3 |                     0 |             4 |      4 | 5, Native         |       5 |
 | TaskWarrior       |                0 | 4?                      | 0                      |                            0 |                     ? |             0 |        | ?, Taskd Server   |       5 |
 | TODO.txt          |                0 | 3, description          | 0                      |                            0 |                     ? |             0 |        | ?, with SyncThing |       5 |
 | Google Keep *     |                5 | 2                       | 2                      |                            0 |                     0 |             3 |        | 5, Native         |       4 |
 | Todoist *         |                0 | 4                       |                        |                              |                     ? |             0 |        | 4                 |       2 |
 | TickTick *        |                0 | 5                       |                        |                              |                     4 |             0 |        | 3, Linux (o:      |       1 |
 | Zim               |                  |                         |                        |                              |                       |               |        |                   |       5 |
 | TiddlyWiki        |                  |                         |                        |                              |                       |               |        |                   |       5 |
 | Standard Note     |                  |                         |                        |                              |                       |               |        |                   |       5 |
 | Hugo              |                0 | 0                       | 0                      |                          4.5 |                     0 |             0 |        | 0                 |       5 |
 |                   |                  |                         |                        |                              |                       |               |        |                   |         |
